#---------------------------------------------------------------------
# GitHub Action Workflow Basics
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: Start-GisMeteoJSONParser

on: [workflow_dispatch, push]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
      
    - name: Git clone my repo
      uses: actions/checkout@v1   
    
    - name: Lets test some packages if they are here 1
      run : aws --version

    - name: Lets test some packages if they are here 2
      run : zip --version
