#---------------------------------------------------------------------
# GitHub Action Workflow Basics
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: Start-GisMeteoJSONParser

on: [workflow_dispatch, push]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
      
    - name: Git clone my repo
      uses: actions/checkout@v2
    
    - name: Create report file
      run: date +%s > report.txt

    - name: Commit report
      run: |
        git config --global user.name 'ElectoMadMan'
        git config --global user.email 'ElectoMadMan@users.noreply.github.com'
        git commit -am "Automated report"
        git push
